nome = input('Digite seu nome completo: ').strip()
print('='*43)
print('Maiúsculas: ', nome.upper())
print('='*43)
print('Minúsculas: ', nome.lower())
print('='*43)
print('Total de letras: ', len(nome))
print('='*43)
print('Quantidade de letras no primeiro nome: ',len(nome)-nome.count(' '))
print('='*43)
